name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - run: pip install -r requirements.txt

      - name: Build the executable file
        run: |
          pyinstaller t4auto.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: t4auto
          path: dist/**/*

  release:
    needs: build
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: t4auto

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "${tag}" `
              --repo="$GITHUB_REPOSITORY" `
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" `
              --notes "Release for ${tag}" `
              "dist/**/*"
